name: readme

on:
  push:
    branches:
      - $default-branch
    paths:
      - README.md
      - .github/workflows/readme.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Push readme
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: webhippie/alpine
          provider: dockerhub
          short_description: Docker images for Alpine
          readme_file: README.md

  quayio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Push readme
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.QUAY_APIKEY }}
        with:
          destination_container_repo: quay.io/webhippie/alpine
          provider: quay
          readme_file: README.md
